# Allocation Algorithm 9

> **1.** Create a list of dataframes.  Each dataframe consists of an EI and all the children assigned to that EI in the real data

> **2.** Create a cluster center with is an average of these values for each dataframe that is then averaged with the EI values to create a weighted cluster center leaning towards the EI

> **3.** Assign children to clusters (children in random order).  After an EI has 17 children, no more children are assigned to them to create somewhat even distribution

> **4.** Push allocation to MySQL table locationdataalgo6

In [1]:
import pandas as pd
import numpy as np
import mysql.connector

In [2]:
connection = mysql.connector.connect(
            host = "localhost",
            port = 3306,
            user = 'root',
            database = "expandinghorizons",
            password = "dB79@dG2024!"
)
    
cursor = connection.cursor()

query = ("Select ei_id, longitude, latitude from ei "
         "WHERE ei_id != '65d75e28e09e67e025e8cd3c'")
cursor.execute(query)

ei_ids = cursor.fetchall()

eiDFs = []

for ei in ei_ids:
    ei_group_list = []
    data = {}
    data["id"] = ei[0]
    data["longitude"] = ei[1]
    data["latitude"] = ei[2]
    ei_child_query = ("SELECT child_id_1, ei_id_1, driving_distance, driving_time "
                      "FROM locationdata "
                      f"WHERE ei_id_1 = '{ei[0]}' AND child_id_2 IS NULL AND ei_id_2 IS NULL")
    cursor.execute(ei_child_query)
    ei_child = cursor.fetchall()
    
    for row2 in ei_child:
        # Add columns with prefixes
        data[f'{row2[0]}_distance'] = row2[2]
        data[f'{row2[0]}_time'] = row2[3]
        
    ei1_ei_query = ("SELECT ei_id_1, ei_id_2, driving_distance, driving_time "
                    "FROM locationdata "
                    f"WHERE ei_id_1 = '{ei[0]}' AND child_id_1 is NULL and child_id_2 is NULL")
    cursor.execute(ei1_ei_query)
    ei1_ei = cursor.fetchall()
    
    for row3 in ei1_ei:
        data[f'{row3[1]}_distance'] = row3[2]
        data[f'{row3[1]}_time'] = row3[3]
    
    ei_ei2_query = ("SELECT ei_id_1, ei_id_2, driving_distance, driving_time "
                    "FROM locationdata "
                    f"WHERE ei_id_2 = '{ei[0]}' AND child_id_1 is NULL and child_id_2 is NULL")
    cursor.execute(ei_ei2_query)
    ei_ei2 = cursor.fetchall()
    
    for row4 in ei_ei2:
        data[f'{row4[0]}_distance'] = row4[2]
        data[f'{row4[0]}_time'] = row4[3]
        
    ei_group_list.append(data)
    
    childQuery = ("SELECT child.child_id, child.longitude, child.latitude FROM locationdatareal ld "
                  "join child on child.child_id = ld.child_id_1 "
                  f"where child_id_2 is null and ei_id_2 is null and ld.assigned = 1 and ei_id_1 = '{ei[0]}'")
    
    cursor.execute(childQuery)
    assignedChild = cursor.fetchall()
    
    for child in assignedChild:
        data = {}
        data["id"] = child[0]
        data["longitude"] = child[1]
        data["latitude"] = child[2]
        child1_child_query = ("SELECT child_id_1, child_id_2, driving_distance, driving_time "
                              "FROM locationdata "
                              f"WHERE child_id_1 = '{child[0]}' AND ei_id_1 IS NULL AND ei_id_2 IS NULL")
        cursor.execute(child1_child_query)
        child1_child = cursor.fetchall()

        for row2 in child1_child:
            # Add columns with prefixes
            data[f'{row2[1]}_distance'] = row2[2]
            data[f'{row2[1]}_time'] = row2[3]

        child_child2_query = ("SELECT child_id_1, child_id_2, driving_distance, driving_time "
                              "FROM locationdata "
                              f"WHERE child_id_2 = '{child[0]}' AND ei_id_1 IS NULL AND ei_id_2 IS NULL")
        cursor.execute(child_child2_query)
        child_child2 = cursor.fetchall()

        for row3 in child_child2:
            data[f'{row3[0]}_distance'] = row3[2]
            data[f'{row3[0]}_time'] = row3[3]

        child_ei_query = ("SELECT child_id_1, ei_id_1, driving_distance, driving_time "
                          "FROM locationdata "
                          f"WHERE child_id_1 = '{child[0]}' AND child_id_2 IS NULL AND ei_id_2 IS NULL")
        cursor.execute(child_ei_query)
        child_ei = cursor.fetchall()

        for row4 in child_ei:
            data[f'{row4[1]}_distance'] = row4[2]
            data[f'{row4[1]}_time'] = row4[3]

        ei_group_list.append(data)
    eiDataFrame = pd.DataFrame(ei_group_list)
    eiDataFrame = eiDataFrame.fillna(0)
    eiDFs.append(eiDataFrame)

In [3]:
clusterCenters = pd.DataFrame()
for df in eiDFs:
    for index, row in df.iterrows():
        ei_row = row
        ei_row = ei_row.to_frame()
        ei_row = ei_row.transpose()
        break
    id_value = df.loc[0, "id"]
    df = df.drop(columns=["id"])
    new_row = df.mean()
    new_row = new_row.to_frame()
    new_row = new_row.transpose()
    
    meanDF = pd.concat([ei_row, new_row], ignore_index = True)
    meanDF = meanDF.drop(columns=["id"])
    clusterCenterPoint = meanDF.mean()
    clusterCenterPoint["id"] = id_value
    clusterCenterPoint["assignment_count"] = 0
    clusterCenterPoint = clusterCenterPoint.to_frame()
    clusterCenterPoint = clusterCenterPoint.transpose()
    clusterCenters = pd.concat([clusterCenters, clusterCenterPoint], ignore_index = True)

print(clusterCenters)

    longitude   latitude 65d8d05fe09e67e025e8cda9_distance  \
0  -82.376027  36.333302                           25.9935
1   -82.03539  36.629112                         64.636575
2  -82.957477  36.238022                          23.76747
3  -82.442713  36.305203                         21.662037
4  -82.055566  36.424277                           48.3988
5  -82.547454  36.521234                         43.616834
6    -82.6565  36.475722                         41.236624
7  -82.532677  36.276078                         17.412283
8  -82.214112   36.57496                         53.418653
9  -82.314368  36.321829                           27.4471
10  -82.29029  36.345866                         33.175034
11 -82.548537  36.532149                         41.636939

   65d8d05fe09e67e025e8cda9_time 65d8d732e09e67e025e8cdb6_distance  \
0                      36.295597                         25.889342
1                      76.202842                         16.162758
2                       34.12663                         59.117113
3                      32.159687                          29.80735
4                      68.221942                         25.927938
5                      54.148009                         28.252875
6                      53.994683                         35.324487
7                      25.466834                         34.816018
8                      65.259384                          5.242888
9                      37.989758                         28.203442
10                     46.972382                         25.235472
11                     53.986193                          27.45598

   65d8d732e09e67e025e8cdb6_time 65d8d7c4e09e67e025e8cdb7_distance  \
0                      37.492824                         25.889342
1                      25.622048                         16.162758
2                      66.581413                         59.117113
3                      42.923508                          29.80735
4                      40.431617                         25.927938
5                      36.569853                         28.252875
6                      43.890996                         35.324487
7                      49.054935                         34.816018
8                      10.855155                          5.242888
9                      39.739104                         28.203442
10                     36.345518                         25.235472
11                     37.355054                          27.45598

   65d8d7c4e09e67e025e8cdb7_time 65d8bec4e09e67e025e8cd8b_distance  \
0                      37.492824                         44.824576
1                      25.622048                         66.227842
2                      66.581413                         21.149175
3                      42.923508                         45.492513
4                      40.431617                         72.409929
5                      36.569853                         26.820119
6                      43.890996                         23.972965
7                      49.054935                         41.704729
8                      10.855155                           52.2116
9                      39.739104                         50.400915
10                     36.345518                          51.46619
11                     37.355054                         26.056552

   65d8bec4e09e67e025e8cd8b_time  ... 65d75d4ce09e67e025e8cd37_distance  \
0                      55.202497  ...                          7.050326
1                       76.45095  ...                         43.723467
2                      35.747654  ...                          36.00641
3                      57.737397  ...                          5.146367
4                      88.225267  ...                         33.567208
5                      37.299262  ...                         22.587619
6                      32.620332  ...                          27.99897
7                      56.286571  ...                          5.965378
8                       62.06325  ...                         32.836282
9                      61.274596  ...                         10.692932
10                     63.016294  ...                           14.3618
11                     36.517959  ...                         22.565798

   65d75d4ce09e67e025e8cd37_time 65d75d80e09e67e025e8cd38_distance  \
0                      13.323761                         33.197721
1                      52.190717                         18.889502
2                       44.66916                         56.662457
3                       9.702771                         36.514453
4                       51.86285                         29.594067
5                      29.457019                           25.7956
6                      36.215278                         32.772441
7                       8.733829                         39.551282
8                      40.876437                          3.716947
9                      19.234977                         36.154146
10                     24.426372                         30.575174
11                      29.19832                          25.06925

   65d75d80e09e67e025e8cd38_time 65d75da9e09e67e025e8cd39_distance  \
0                      37.408826                          4.344685
1                      25.137807                         43.750729
2                      59.906723                         42.076963
3                      41.806587                          7.596491
4                      42.906146                           25.2034
5                      29.981681                         24.151238
6                      37.134157                         30.906852
7                      45.286288                         13.135353
8                        6.28899                         32.470682
9                      40.695146                          5.656013
10                     37.712578                         11.153394
11                     30.290263                         24.159315

   65d75da9e09e67e025e8cd39_time 65d75a2ce09e67e025e8cd30_distance  \
0                       8.088193                          2.810574
1                      48.510883                         41.816378
2                      53.689083                          40.46475
3                      13.585201                          6.235271
4                      38.337154                         26.926075
5                       27.78822                         21.692315
6                      35.326263                         28.309241
7                      20.315071                          11.91427
8                      38.111305                         29.776413
9                       9.500381                          6.877848
10                     18.192357                         10.109457
11                     27.563702                         21.701165

   65d75a2ce09e67e025e8cd30_time                        id assignment_count
0                       5.541683  65d75a2ce09e67e025e8cd30                0
1                       49.47485  65d75bb0e09e67e025e8cd31                0
2                       51.42384  65d75c59e09e67e025e8cd32                0
3                      11.843229  65d75c87e09e67e025e8cd33                0
4                      42.232767  65d75cb9e09e67e025e8cd34                0
5                      27.335712  65d75ce1e09e67e025e8cd35                0
6                      34.714317  65d75d08e09e67e025e8cd36                0
7                      18.632009  65d75d4ce09e67e025e8cd37                0
8                        37.0075  65d75d80e09e67e025e8cd38                0
9                      12.792343  65d75da9e09e67e025e8cd39                0
10                     16.830186  65d75dd5e09e67e025e8cd3a                0
11                     26.859161  65d75dfae09e67e025e8cd3b                0

[12 rows x 422 columns]

In [4]:
query = ("SELECT child_id, longitude, latitude FROM child ")
cursor.execute(query)

child_ids = cursor.fetchall()

data_list = []
for row in child_ids:
    data = {}
    data["id"] = row[0]
    data["longitude"] = row[1]
    data["latitude"] = row[2]
    child1_child_query = ("SELECT child_id_1, child_id_2, driving_distance, driving_time "
                          "FROM locationdata "
                          f"WHERE child_id_1 = '{row[0]}' AND ei_id_1 IS NULL AND ei_id_2 IS NULL")
    cursor.execute(child1_child_query)
    child1_child = cursor.fetchall()
    
    for row2 in child1_child:
        # Add columns with prefixes
        data[f'{row2[1]}_distance'] = row2[2]
        data[f'{row2[1]}_time'] = row2[3]
        
    child_child2_query = ("SELECT child_id_1, child_id_2, driving_distance, driving_time "
                          "FROM locationdata "
                          f"WHERE child_id_2 = '{row[0]}' AND ei_id_1 IS NULL AND ei_id_2 IS NULL")
    cursor.execute(child_child2_query)
    child_child2 = cursor.fetchall()
    
    for row3 in child_child2:
        data[f'{row3[0]}_distance'] = row3[2]
        data[f'{row3[0]}_time'] = row3[3]
    
    child_ei_query = ("SELECT child_id_1, ei_id_1, driving_distance, driving_time "
                      "FROM locationdata "
                      f"WHERE child_id_1 = '{row[0]}' AND child_id_2 IS NULL AND ei_id_2 IS NULL")
    cursor.execute(child_ei_query)
    child_ei = cursor.fetchall()
    
    for row4 in child_ei:
        data[f'{row4[1]}_distance'] = row4[2]
        data[f'{row4[1]}_time'] = row4[3]
        
    data_list.append(data)

childDataFrame = pd.DataFrame(data_list)
childDataFrame = childDataFrame.fillna(0)
childDataFrame = childDataFrame.sample(frac=1)
childDataFrame.reset_index(drop=True, inplace=True)
childDataFrame["assigned"] = ""

print(childDataFrame)

                           id  longitude   latitude  \
0    65e5e3c238f826f29267201c -82.677406  36.544746
1    65d764dde09e67e025e8cd44 -82.248543  36.585987
2    65d8d0bee09e67e025e8cdaa -82.459190  36.282085
3    65d8b6f8e09e67e025e8cd7c -82.550194  36.564823
4    65d8c149e09e67e025e8cd8f -83.120811  36.407242
..                        ...        ...        ...
191  65d8b945e09e67e025e8cd81 -82.485680  36.486526
192  65d8c01ee09e67e025e8cd8d -83.012634  36.398029
193  65e5e60a38f826f29267201e -82.625702  36.553909
194  65d786e0e09e67e025e8cd6f -81.828812  36.502979
195  65e5d77e38f826f292672002 -82.394699  36.483261

     65d8d732e09e67e025e8cdb6_distance  65d8d732e09e67e025e8cdb6_time  \
0                             38.74420                        49.2509
1                              5.41753                        13.4520
2                             33.26690                        50.3746
3                             24.21240                        37.3500
4                             67.91910                        79.9098
..                                 ...                            ...
191                           22.54890                        30.6242
192                           61.04020                        72.2000
193                           34.98520                        41.7842
194                           30.94230                        54.2062
195                           21.61530                        28.7075

     65d8d7c4e09e67e025e8cdb7_distance  65d8d7c4e09e67e025e8cdb7_time  \
0                             38.74420                        49.2509
1                              5.41753                        13.4520
2                             33.26690                        50.3746
3                             24.21240                        37.3500
4                             67.91910                        79.9098
..                                 ...                            ...
191                           22.54890                        30.6242
192                           61.04020                        72.2000
193                           34.98520                        41.7842
194                           30.94230                        54.2062
195                           21.61530                        28.7075

     65e5cc1b38f826f292671fed_distance  65e5cc1b38f826f292671fed_time  \
0                             30.78840                        41.2646
1                             35.17580                        40.9408
2                              5.45237                        13.1748
3                             26.81430                        34.4001
4                             59.96330                        71.9235
..                                 ...                            ...
191                           19.69740                        27.7606
192                           53.08440                        64.2137
193                           27.02940                        33.7979
194                           47.84660                        71.4913
195                           20.04600                        29.0634

     65d76ca3e09e67e025e8cd4d_distance  ...  65d75da9e09e67e025e8cd39_time  \
0                              48.1887  ...                        37.7136
1                              51.9277  ...                        36.0063
2                              24.1219  ...                        18.2047
3                              43.6906  ...                        30.2299
4                              37.3885  ...                        68.9050
..                                 ...  ...                            ...
191                            36.3607  ...                        24.3426
192                            28.9793  ...                        61.0520
193                            44.4249  ...                        30.6317
194                            96.9536  ...                        63.8550
195                            43.2127  ...                        24.7993

     65d75dd5e09e67e025e8cd3a_distance  65d75dd5e09e67e025e8cd3a_time  \
0                             28.15950                        35.4045
1                             31.68060                        33.6973
2                              8.17439                        19.7760
3                             23.66140                        27.9208
4                             57.33570                        66.5960
..                                 ...                            ...
191                           16.51320                        22.0335
192                           50.43080                        58.7429
193                           24.39570                        28.3227
194                           48.32760                        69.7368
195                           16.54530                        22.4903

     65d75dfae09e67e025e8cd3b_distance  65d75dfae09e67e025e8cd3b_time  \
0                              9.44518                       17.90500
1                             22.61220                       28.02760
2                             23.84110                       34.48280
3                              2.38230                        7.28444
4                             38.62140                       49.09650
..                                 ...                            ...
191                            6.64815                       14.31920
192                           31.71650                       41.24340
193                            5.68140                       10.82320
194                           67.95630                       81.47000
195                           14.29670                       21.24080

     65d75e28e09e67e025e8cd3c_distance  65d75e28e09e67e025e8cd3c_time  \
0                              31.2592                        40.3911
1                              18.8517                        30.7059
2                              13.8654                        29.6975
3                              26.7610                        32.9074
4                              60.4354                        71.5826
..                                 ...                            ...
191                            13.5251                        26.2114
192                            53.5305                        63.7295
193                            27.4954                        33.3093
194                            63.3073                        85.6053
195                            10.3525                        19.9087

     65d76430e09e67e025e8cd43_distance  65d76430e09e67e025e8cd43_time  \
0                              40.4066                        50.2243
1                              10.0897                        20.9354
2                              28.8923                        47.1253
3                              28.5021                        39.9174
4                              69.5829                        81.4158
..                                 ...                            ...
191                            24.1054                        31.7973
192                            62.6779                        73.5628
193                            36.6429                        43.1425
194                            49.4239                        67.7227
195                            18.5613                        25.8797

     assigned
0
1
2
3
4
..        ...
191
192
193
194
195

[196 rows x 422 columns]

In [5]:
childDataFrameOrdered = childDataFrame.sort_index(axis=1)
clusterCentersOrdered = clusterCenters.sort_index(axis=1)

In [6]:
def euclidean_distance(childRow, eiRow):
    child_values = childRow.drop(['id', 'assigned']).values
    ei_values = eiRow.drop(['id', 'assignment_count']).values
    return np.sqrt(np.sum((child_values - ei_values) ** 2))

In [7]:
childDataFrameAllocate = childDataFrameOrdered.copy()
for child_index, child_row in childDataFrameOrdered.iterrows():
    if childDataFrameAllocate.loc[child_index, "assigned"] == "":
        availableClusters = clusterCentersOrdered[clusterCentersOrdered['assignment_count'] < 17]
        eiDF = pd.DataFrame(columns=["id", "euclidean_distance"])
        for cluster_index, cluster_row in availableClusters.iterrows():
            e_value = euclidean_distance(child_row, cluster_row)
            eiDF = pd.concat([eiDF, pd.DataFrame({"id": [cluster_row["id"]], "euclidean_distance": [e_value]})], ignore_index=True)
        minValue = eiDF["euclidean_distance"].min()
        minIndex = eiDF["euclidean_distance"].idxmin()
        ei_with_min = eiDF.at[minIndex, "id"]

        same_location_children = childDataFrameOrdered[(childDataFrameOrdered["longitude"] == child_row["longitude"]) & 
                                                      (childDataFrameOrdered["latitude"] == child_row["latitude"])]
        childDataFrameOrdered.loc[same_location_children.index, 'assigned'] = ei_with_min
        
        rows_with_ei_with_min = childDataFrameOrdered[childDataFrameOrdered['assigned'] == ei_with_min]
        count_ei_with_min = len(rows_with_ei_with_min)
        
        clusters_index = clusterCentersOrdered[clusterCentersOrdered['id'] == ei_with_min].index
        clusterCentersOrdered.at[clusters_index[0], 'assignment_count'] = count_ei_with_min
    else:
        print("child already assigned")
    childDataFrameAllocate = childDataFrameOrdered.copy()

print(clusterCentersOrdered)

child already assigned
child already assigned
child already assigned
child already assigned
child already assigned
child already assigned
child already assigned
child already assigned
child already assigned
child already assigned
child already assigned
child already assigned
child already assigned
child already assigned
child already assigned
child already assigned
child already assigned
child already assigned
child already assigned
child already assigned
   65d75a2ce09e67e025e8cd30_distance 65d75a2ce09e67e025e8cd30_time  \
0                           2.810574                      5.541683
1                          41.816378                      49.47485
2                           40.46475                      51.42384
3                           6.235271                     11.843229
4                          26.926075                     42.232767
5                          21.692315                     27.335712
6                          28.309241                     34.714317
7                           11.91427                     18.632009
8                          29.776413                       37.0075
9                           6.877848                     12.792343
10                         10.109457                     16.830186
11                         21.701165                     26.859161

   65d75bb0e09e67e025e8cd31_distance 65d75bb0e09e67e025e8cd31_time  \
0                          50.328468                     55.278708
1                          11.390842                       15.7992
2                           73.40462                     76.824027
3                          53.547766                     58.445408
4                          37.436054                     50.076338
5                          42.290641                     46.508834
6                          49.146857                     53.474817
7                          56.188794                     61.750335
8                          21.360658                        27.371
9                          51.402608                     55.929008
10                         47.684236                     54.663624
11                         41.485837                     46.823974

   65d75c59e09e67e025e8cd32_distance 65d75c59e09e67e025e8cd32_time  \
0                           39.68105                     48.751811
1                          68.676825                     72.520033
2                           7.452198                     10.908296
3                          34.290158                     43.354537
4                          74.307071                     83.955538
5                          41.596806                     45.893659
6                          34.408957                     41.343954
7                          27.431699                     35.089244
8                          54.477321                     57.951042
9                          44.100104                     55.190235
10                          53.18454                      58.71517
11                          40.92253                     44.958815

   65d75c87e09e67e025e8cd33_distance 65d75c87e09e67e025e8cd33_time  \
0                           5.341362                     11.240627
1                          43.927883                      52.15495
2                          39.574763                      49.90797
3                           4.076779                      7.091531
4                          29.623146                     47.607187
5                          23.373506                     30.666275
6                          29.965389                     37.985789
7                           10.00781                     15.463777
8                          32.596103                     40.916524
9                           8.764991                      16.53158
10                         12.676889                     21.729937
11                         23.378611                        30.124

   65d75cb9e09e67e025e8cd34_distance 65d75cb9e09e67e025e8cd34_time  ...  \
0                          14.337078                     24.248322  ...
1                          32.460846                     40.934679  ...
2                           59.32214                      69.57831  ...
3                          19.268026                     31.674621  ...
4                          16.487904                     23.216287  ...
5                          32.018305                     40.231716  ...
6                           39.63325                     48.399017  ...
7                             25.196                     39.374129  ...
8                          19.451963                     28.413871  ...
9                           14.45185                     23.628638  ...
10                         14.010733                     24.451827  ...
11                         33.231657                     41.281726  ...

   65e6044938f826f292672031_distance 65e6044938f826f292672031_time  \
0                          23.991153                     28.931842
1                          36.742917                     48.173142
2                          41.570193                      46.58945
3                          25.633416                     31.942532
4                          48.802775                     61.151137
5                           6.216561                      12.15039
6                          16.332833                     22.141853
7                          27.929506                     35.614424
8                          22.325654                     33.914455
9                          29.092492                     34.996038
10                         29.632842                     36.485712
11                          3.927182                      9.144632

   65e6049b38f826f292672032_distance 65e6049b38f826f292672032_time  \
0                          23.731321                     28.098487
1                          36.284458                     46.328817
2                            41.4729                     45.766447
3                          25.536129                     31.119529
4                          45.228383                     59.742179
5                           5.880414                     10.650253
6                          16.235607                     21.318851
7                          27.832276                     34.791418
8                          21.844731                     32.006666
9                          28.964896                     34.087338
10                         29.496206                       35.5513
11                          3.564846                       7.59509

   65ef076606e0a866af56d202_distance 65ef076606e0a866af56d202_time  \
0                           52.51585                     79.224371
1                          35.928068                     57.538167
2                          103.41235                      122.5052
3                          57.206521                     85.935971
4                          29.759895                     45.088363
5                          74.794141                     92.231906
6                          82.736652                    100.377722
7                          63.146079                     93.055288
8                          50.248518                     70.661392
9                          46.710446                     70.842465
10                         49.738364                     73.906542
11                         74.466687                     93.918317

   assignment_count                        id   latitude  longitude
0                17  65d75a2ce09e67e025e8cd30  36.333302 -82.376027
1                 9  65d75bb0e09e67e025e8cd31  36.629112  -82.03539
2                17  65d75c59e09e67e025e8cd32  36.238022 -82.957477
3                17  65d75c87e09e67e025e8cd33  36.305203 -82.442713
4                17  65d75cb9e09e67e025e8cd34  36.424277 -82.055566
5                17  65d75ce1e09e67e025e8cd35  36.521234 -82.547454
6                17  65d75d08e09e67e025e8cd36  36.475722   -82.6565
7                17  65d75d4ce09e67e025e8cd37  36.276078 -82.532677
8                17  65d75d80e09e67e025e8cd38   36.57496 -82.214112
9                17  65d75da9e09e67e025e8cd39  36.321829 -82.314368
10               17  65d75dd5e09e67e025e8cd3a  36.345866  -82.29029
11               17  65d75dfae09e67e025e8cd3b  36.532149 -82.548537

[12 rows x 422 columns]

In [8]:
for index, cluster in clusterCentersOrdered.iterrows():
    cluster_id = cluster["id"]
    rows_with_ei_with_min = childDataFrameOrdered[childDataFrameOrdered['assigned'] == cluster_id]
    count_ei_with_min = len(rows_with_ei_with_min)
    print(f"children assigned to this ei: {count_ei_with_min}")

children assigned to this ei: 17
children assigned to this ei: 9
children assigned to this ei: 17
children assigned to this ei: 17
children assigned to this ei: 17
children assigned to this ei: 17
children assigned to this ei: 17
children assigned to this ei: 17
children assigned to this ei: 17
children assigned to this ei: 17
children assigned to this ei: 17
children assigned to this ei: 17

In [9]:
for index, child in childDataFrameOrdered.iterrows():
    child_id = child["id"]
    ei_id = child["assigned"]
    updateQuery = ("Update locationdataalgo9 "
                   "SET assigned = 1 "
                   f"WHERE child_id_1 = '{child_id}' and ei_id_1 = '{ei_id}' and child_id_2 is NULL and ei_id_2 is NULL")
    cursor.execute(updateQuery)
    connection.commit()
    print("Update query pushed")

Update query pushed
Update query pushed
Update query pushed
Update query pushed
Update query pushed
Update query pushed
Update query pushed
Update query pushed
Update query pushed
Update query pushed
Update query pushed
Update query pushed
Update query pushed
Update query pushed
Update query pushed
Update query pushed
Update query pushed
Update query pushed
Update query pushed
Update query pushed
Update query pushed
Update query pushed
Update query pushed
Update query pushed
Update query pushed
Update query pushed
Update query pushed
Update query pushed
Update query pushed
Update query pushed
Update query pushed
Update query pushed
Update query pushed
Update query pushed
Update query pushed
Update query pushed
Update query pushed
Update query pushed
Update query pushed
Update query pushed
Update query pushed
Update query pushed
Update query pushed
Update query pushed
Update query pushed
Update query pushed
Update query pushed
Update query pushed
Update query pushed
Update query pushed
Update query pushed
Update query pushed
Update query pushed
Update query pushed
Update query pushed
Update query pushed
Update query pushed
Update query pushed
Update query pushed
Update query pushed
Update query pushed
Update query pushed
Update query pushed
Update query pushed
Update query pushed
Update query pushed
Update query pushed
Update query pushed
Update query pushed
Update query pushed
Update query pushed
Update query pushed
Update query pushed
Update query pushed
Update query pushed
Update query pushed
Update query pushed
Update query pushed
Update query pushed
Update query pushed
Update query pushed
Update query pushed
Update query pushed
Update query pushed
Update query pushed
Update query pushed
Update query pushed
Update query pushed
Update query pushed
Update query pushed
Update query pushed
Update query pushed
Update query pushed
Update query pushed
Update query pushed
Update query pushed
Update query pushed
Update query pushed
Update query pushed
Update query pushed
Update query pushed
Update query pushed
Update query pushed
Update query pushed
Update query pushed
Update query pushed
Update query pushed
Update query pushed
Update query pushed
Update query pushed
Update query pushed
Update query pushed
Update query pushed
Update query pushed
Update query pushed
Update query pushed
Update query pushed
Update query pushed
Update query pushed
Update query pushed
Update query pushed
Update query pushed
Update query pushed
Update query pushed
Update query pushed
Update query pushed
Update query pushed
Update query pushed
Update query pushed
Update query pushed
Update query pushed
Update query pushed
Update query pushed
Update query pushed
Update query pushed
Update query pushed
Update query pushed
Update query pushed
Update query pushed
Update query pushed
Update query pushed
Update query pushed
Update query pushed
Update query pushed
Update query pushed
Update query pushed
Update query pushed
Update query pushed
Update query pushed
Update query pushed
Update query pushed
Update query pushed
Update query pushed
Update query pushed
Update query pushed
Update query pushed
Update query pushed
Update query pushed
Update query pushed
Update query pushed
Update query pushed
Update query pushed
Update query pushed
Update query pushed
Update query pushed
Update query pushed
Update query pushed
Update query pushed
Update query pushed
Update query pushed
Update query pushed
Update query pushed
Update query pushed
Update query pushed
Update query pushed
Update query pushed
Update query pushed
Update query pushed
Update query pushed
Update query pushed
Update query pushed
Update query pushed
Update query pushed
Update query pushed
Update query pushed
Update query pushed
Update query pushed
Update query pushed
Update query pushed
Update query pushed
Update query pushed
Update query pushed
Update query pushed
Update query pushed
Update query pushed
Update query pushed